feat(core): gds-option-header primitive
sebgroup/green pull request #1203
Opened 2024-02-07 11:54 UTC by vsjolander

2024-02-07 12:10 UTC, splashdust requested changes
Looks super good! Just one issue related to custom element scoping (see review comment)

2024-02-07 19:48 UTC, vsjolander commented
@splashdust I needed to add gds-elements to the lookup table even if the scoping is turned off for your suggestion to work in both cases. Not sure if this was the right solution?

Also changed the name to `gds-option-heading` since it seemed more appropriate and added support in react and angular.

2024-02-08 15:15 UTC, splashdust requested changes
Here's what we discussed: We rename `gds-option-heading` &rarr; `gds-menu-heading`, and allow it in both Context menu and Dropdown.

2024-02-14 15:51 UTC, splashdust approved these changes

2024-02-14 15:52 UTC, merged