refactor: 💡 Refactored tab component
sebgroup/green pull request #368
Opened 2022-01-26 05:33 UTC by terrance456

Added onTabChange functionality and added disabled feature for tabs and added styles in chrolophyll

![screencapture-localhost-4200-2022-01-26-13_25_54](https://user-images.githubusercontent.com/92840841/151108651-4296810b-55d4-45c4-b5aa-ecccd7d1d642.png)

What you guys think about the tabs disabled? Should it look like this or there is a specfic styling for tab disabled in chlorophyll ? Let me know what you guys think about it. @hjalmers @JohanObrink 

![3](https://user-images.githubusercontent.com/92840841/151108911-274d56bd-527f-4d55-b043-a32c8b56114f.PNG)

2022-01-26 05:39 UTC, sebopensource commented
👋 Thanks for creating a pull request! 🚀 Checkout the storybook we created for it [here](https://sebgroup.github.io/green/pr-368/chlorophyll/).

2022-01-26 05:42 UTC, terrance456 commented
https://sebgroup.github.io/green/pr-368/react/?path=/docs/components-tabs--tabs

2022-01-28 08:29 UTC, hjalmers requested changes

2022-01-28 08:29 UTC, hjalmers commented on libs/react/src/lib/tabs/tabs.tsx
> +            data-disabled={value.disabled}
Use aria-disabled instead and  omit href attribute when disabled. I've updated chlorophyll which now inherits behaviour from normal link, se updated storybook [here](https://sebgroup.github.io/green/pr-368/chlorophyll/?path=/docs/components-tabs--page#tabs-with-disabled-tab).

2022-02-01 10:36 UTC, hjalmers approved these changes

2022-02-08 15:33 UTC, hjalmers approved these changes

2022-02-08 15:33 UTC, merged